// <auto-generated />
namespace Visionet.MusicWebsite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SetManyToManyUsrs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetManyToManyUsrs));
        
        string IMigrationMetadata.Id
        {
            get { return "201707170401519_SetManyToManyUsrs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
