// <auto-generated />
namespace Visionet.MusicWebsite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_user_music : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_user_music));
        
        string IMigrationMetadata.Id
        {
            get { return "201707170332283_add_user_music"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
